package com.eka.medassist.ui.chat.presentation.states

enum class ActionType(val stringValue: String) {
    OPEN_INPUT_BOTTOM_SHEET("OPEN_INPUT_BOTTOM_SHEET"),
    ON_CAMERA_CLICK("ON_CAMERA_CLICK"),
    ON_GALLERY_CLICK("ON_GALLERY_CLICK"),
    START_CHAT("START_CHAT"),
    ON_BACK("ON_BACK"),
    SHOW_INPUT_BOTTOM_SHEET("SHOW_INPUT_BOTTOM_SHEET"),
    ON_POSITIVE_REVIEW_CLICKED("ON_POSITIVE_REVIEW_CLICKED"),
    ON_NEGETIVE_REVIEW_CLICKED("ON_NEGETIVE_REVIEW_CLICKED"),
    ON_COPY_CLICKED("ON_COPY_CLICKED"),
    ON_SHARE_CLICKED("ON_SHARE_CLICKED"),
    ON_CHAT_MESSAGE_CLICKED("ON_CHAT_MESSAGE_CLICKED"),
}